server:
  port: 8114

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    url: jdbc:mysql://localhost:3306/linsen?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    devtools:
      restart:
        enabled: true
    jpa:
      show-sql: true
      database: mysql
      hibernate.ddl-auto: update
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


