#server:
#  port: 8112
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/linsen?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    devtools:
#      restart:
#        enabled: true
#    jpa:
#      show-sql: true
#      database: mysql
#      hibernate.ddl-auto: update
#      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#      database-platform: org.hibernate.dialect.MySQL5Dialect
#      hibernate:
#        naming:
#          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#  mail:
#    default-encoding: utf-8
#    host: smtp.qq.com
#    username: 1814422053@qq.com
#    password: cglocmbilohkcbca
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
