server:
  port: 8001
spring:
  application:
    name: nacos-getway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gateway-plan
          uri: lb://work-plan-service
          predicates:
            - Path=/plan/**
        - id: gateway-auth
          uri: lb://auth-service
          predicates:
            - Path=/user/**
        - id: gateway-shares
          uri: lb://linsen-shares
          predicates:
            - Path=/shares/**


publicKey: D:\\public_key.txt

